### PR TITLE
Expose focus item

### PR DESCRIPTION
**Pull request by LeopoldoFu**
@ebsco/developers

### CODE REVIEW

**Comment by LeopoldoFu** [comment]
We basically need these changes in order to focus on the first item when the dropdown is open as per the [wai-aria practices](https://www.w3.org/TR/wai-aria-practices/#menu).

**Comment by leachryanb** [comment]
Looks good. Shouldn't this be a PR back to the original repo?

**Comment by LeopoldoFu** [comment]
@leachryanb I wanted to be sure we have this available ASAP. I will make a PR to the original repo after you guys have vetted this.

**Comment by esimons** [comment]
Isn't this option already made available by the library?
https://github.com/davidtheclark/react-aria-menubutton#openmenuwrapperid-openoptions

**Comment by LeopoldoFu** [comment]
Apparently I can't @ target evan. So here is my response regardless: 

That doesn't work for us. We can override the click handler on the Wrapper, but then we don't have access to the state of whether the dropdown is open or not in order to close the dropdown when open.

There is already a [related issue of exposing the dropdown state](https://github.com/davidtheclark/react-aria-menubutton/issues/48). So it does look like something along these lines should be exposed to faciliate what we're doing.

**Review by leachryanb — APPROVED** [review]

**Comment by esimons** [comment]
If you need the state of the dropdown available in the wrapper component, can you use a ref? Internal component state should be accessible via that route.

**Comment by LeopoldoFu** [comment]
We're actually going with doing it like this

``` javascript
<AriaMenu className="AriaMenuContent" data-auto="menu" tag="ul" {...other}>
    {({ isOpen }) => {
        let menuChildren = null;
        if (isOpen) {
            menuChildren = children;
            focusItem(id, 0);
        }
        return menuChildren;
    }}
</AriaMenu>
```

So it's working with what is already available in the library. I don't know if exposing ref is better.

**Comment by reggersusa** [comment]
I'll look into it...

```
  From: LeopoldoFu <notifications@github.com>
```

 To: ebsco/react-aria-menubutton react-aria-menubutton@noreply.github.com 
Cc: reggersusa reggersusa@yahoo.com; Team mention team_mention@noreply.github.com
 Sent: Thursday, October 6, 2016 3:54 PM
 Subject: Re: [ebsco/react-aria-menubutton] Expose focus item (#1)

We're actually going with doing it like this<AriaMenu className="AriaMenuContent" data-auto="menu" tag="ul" {...other}>
    {({ isOpen }) => {
        let menuChildren = null;
        if (isOpen) {
            menuChildren = children;
            focusItem(id, 0);
        }
        return menuChildren;
    }}
</AriaMenu>So it's working with is already avaiable in the library. I don't know if exposing ref is better.—

**Comment by RichCaloggero** [comment]
The demo at:
http://davidtheclark.github.io/react-aria-menubutton/demo/

does not seem to exhibit the focus to first menu item when menu opens behavior which was supposedly incorporated:
https://github.com/ebsco/react-aria-menubutton/pull/1

- Is this meant to be optional or default behavior

The "fancy demo" at the above url does exhibit the behavior if you click the "open menu below with focus" button, and this works well!  However, clicking the "open menu below" button, focus is not sent to the first menu item.

**Pull request merged**
